import argparse
from pathlib import Path

import joblib

from jsbsim_gym.calibration import export_nominal_coefficient_weights


def _load_artifact_with_legacy_nominalmodel_support(artifact_path: Path):
    try:
        return joblib.load(artifact_path)
    except AttributeError as exc:
        # Older artifacts serialized from direct script execution may reference
        # __main__.NominalModel. Rebind that symbol and retry loading.
        if "NominalModel" not in str(exc):
            raise

        import __main__
        from jsbsim_gym.calibration import NominalModel

        if not hasattr(__main__, "NominalModel"):
            __main__.NominalModel = NominalModel
        return joblib.load(artifact_path)


def export_from_calibration_artifact(artifact_path: Path, output_path: Path) -> None:
    artifact = _load_artifact_with_legacy_nominalmodel_support(artifact_path)
    if "nominal_model" not in artifact:
        raise ValueError(
            f"Calibration artifact {artifact_path} does not contain 'nominal_model'. "
            "Run calibration first via: python -m jsbsim_gym.calibration"
        )

    nom_model = artifact["nominal_model"]
    if not hasattr(nom_model, "coeff_models") or not hasattr(nom_model, "coeff_targets"):
        raise ValueError(
            "Loaded nominal model is missing coefficient model fields. "
            "Regenerate artifact with current calibration pipeline."
        )

    source_dataset = artifact.get("source_dataset", "f16_dataset.parquet")
    exported_path = export_nominal_coefficient_weights(
        nom_model,
        output_path=str(output_path),
        source_dataset=str(source_dataset),
    )
    print(f"Exported nominal coefficient weights from {artifact_path} to {exported_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export nominal coefficient weights from an existing calibration artifact. "
            "This does not refit the model."
        )
    )
    parser.add_argument(
        "--artifact",
        type=Path,
        default=Path("f16_uncertainty_model.pkl"),
        help="Path to calibration artifact generated by jsbsim_gym.calibration.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("jsbsim_gym/nominal_coeff_weights.npz"),
        help="Output NPZ path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    export_from_calibration_artifact(args.artifact, args.output)


if __name__ == "__main__":
    main()
